### ISSUE TITLE
maxSelect

### ISSUE THREAD

**Issue by rossanodr** [zenzillo/-zenzillo-react-native-select-multiple#3]
Does the max Select works on android?
It seams that is not working for me, Even though I set max number I can select more

**Comment by zenzillo** [comment]
You're right, @rossanodr! maxSelect was not working. It looks like the functionality was removed in the code that I forked. I added it back to the latest published version 1.1.1. 

Once you update this package it should be working for you. Let me know if it doesn't though. 

Thanks for making this better!

**Comment by zenzillo** [comment]
npm version 1.1.1 also available at [https://www.npmjs.com/package/@zenzillo/react-native-select-multiple](https://www.npmjs.com/package/@zenzillo/react-native-select-multiple)
